#!/bin/bash
set -e

sudo docker run -d -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 mysql:5.7

sleep 5
sudo docker run -d -p 6379:6379 redis

sleep 5
sudo docker run -d --net=host archci/archci

sleep 5
sudo docker run -d --net=host --privileged archci/simple-docker
