#!/bin/bash

sudo docker run -d -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 mysql:5.7

sudo docker run -d -p 6379:6379 redis

sudo docker run -d --net=host archci/archci

sudo docker run -d --net=host archci/simple-docker
